name: apod
description: "Receive the daily astronomy picture of the day."
publish_to: 'none'
version: 2.0.5

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  change_app_package_name: ^1.1.0
  envied: ^0.5.3
  file_picker: ^8.0.0+1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^17.2.2
  home_widget: ^0.7.0+1
  http: ^1.2.1
  logger: ^2.5.0
  lottie: ^3.1.2
  path: ^1.9.0
  permission_handler: ^11.3.1
  provider: ^6.1.2
  timezone: ^0.9.4
  youtube_player_iframe: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  envied_generator: ^0.5.3
  build_runner: ^2.4.8
  mockito: ^5.4.4
  network_image_mock: ^2.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/animations/

flutter_launcher_icons:
  image_path: "assets/launcher_icon/android/play_store_512.png"
  android: true # can specify file name here e.g. "ic_launcher"
  adaptive_icon_background: "assets/launcher_icon/android/res/mipmap-xxxhdpi/ic_launcher_background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/launcher_icon/android/res/mipmap-xxxhdpi/ic_launcher_foreground.png" # only available for Android 8.0 devices and above
  adaptive_icon_monochrome: "assets/launcher_icon/android/res/mipmap-xxxhdpi/ic_launcher_monochrome.png" # only available for Android 13 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  ios: true
